# config.yaml

# Global settings
device: "cuda" # or "cpu"

# Training settings
epochs: 5
batch_size: 32
learning_rate: 0.001

# RCL (EWC) specific settings
lambda_reg: 0.1

# LwF specific settings
alpha_lwf: 1.0 # Weight for distillation loss
temperature: 2.0 # Temperature for LwF softmax

# Dataset settings
adult_census:
  test_size: 0.2
  random_state: 42
compas:
  test_size: 0.2
  random_state: 42
fairface:
  test_size: 0.2 # Placeholder
  random_state: 42 # Placeholder
