# Responsible AI Framework Configuration

# Nguyên tắc cốt lõi
principles:
  fairness: true
  transparency: true
  privacy: true
  accountability: true
  explainability: true
  robustness: true

# Cấu hình Fairness
fairness:
  metrics:
    - demographic_parity
    - equalized_odds
    - equal_opportunity
    - disparate_impact
  sensitive_attributes:
    - gender
    - age
    - race
    - ethnicity
  threshold: 0.8  # Ngưỡng chấp nhận cho fairness metrics

# Cấu hình Privacy
privacy:
  differential_privacy:
    enabled: true
    epsilon: 1.0  # Privacy budget
    delta: 1e-5
  data_anonymization: true
  pii_detection: true

# Cấu hình Explainability
explainability:
  methods:
    - shap
    - lime
    - feature_importance
  generate_reports: true
  
# Cấu hình Audit
audit:
  enabled: true
  log_predictions: true
  log_decisions: true
  retention_days: 90

# Cấu hình Monitoring
monitoring:
  model_drift_detection: true
  performance_tracking: true
  bias_monitoring: true
  alert_threshold: 0.1

